image:
  repository: kong/kong-gateway
  tag: "3.7.0.0"

secretVolumes:
- kong-cluster-cert

admin:
  enabled: false

extraLabels:
  tags.datadoghq.com/env: "demo"
  tags.datadoghq.com/service: "kong-dp"
  tags.datadoghq.com/version: "3.7.0.0"

# Annotation to be added to Kong pods
podAnnotations:
  kuma.io/gateway: enabled
  traffic.sidecar.istio.io/includeInboundPorts: ""
  ad.datadoghq.com/proxy.check_names: '["kong"]'
  ad.datadoghq.com/proxy.init_configs: '[{}]'
  ad.datadoghq.com/proxy.instances: '[{"openmetrics_endpoint": "http://%%host%%:8100/metrics"}]'
  ad.datadoghq.com/proxy.logs: '[{"source": "kong", "service": "kong-proxy"}]'

env:
  role: data_plane
  database: "off"
  cluster_mtls: pki
  lua_ssl_trusted_certificate: system
  konnect_mode: "on"
  vitals: "off"
  tracing_instrumentations: "all"
  tracing_sampling_rate: "1.0"
  status_listen: "0.0.0.0:8100 http2"
  port_maps: "80:8000, 443:8443, 8100:8100"

ingressController:
  enabled: false
  installCRDs: false

serviceMonitor:
  # Specifies whether ServiceMonitor for Prometheus operator should be created
  # If you wish to gather metrics from a Kong instance with the proxy disabled (such as a hybrid control plane), see:
  # https://github.com/Kong/charts/blob/main/charts/kong/README.md#prometheus-operator-integration
  enabled: true
  interval: 30s
  # Specifies namespace, where ServiceMonitor should be installed
  namespace: kong-observability
  labels:
    release: kong-prometheus
  targetLabels:
    - release