name: Contract Mock Testing

on:
  workflow_call:
    inputs:
      openapi_file:
        description: 'OpenAPI file path'
        type: string
        default: 'flights/openapi.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    name: Mock testing with inso, schemathesis and wiremock
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Wiremock
        id: setup-wiremock
        run: |
          container_id=$(docker run -d --rm \
          -p 8080:8080 \
          --name wiremock \
          -v ${{ github.workspace }}/mock:/home/wiremock \
          wiremock/wiremock:3.10.0)
          echo "container_id=$container_id" >> $GITHUB_ENV
      
      - name: Get the WireMock standard output
        run: echo "${{ steps.setup-wiremock.outputs.wiremock-stdout }}"

      - name: Generate K6 script from openapi
        uses: hatamiarash7/openapi-generator@v0.3.0
        with:
          openapi-file: "${{ inputs.openapi_file }}"
          generator: 'k6'
          output-dir: 'flights/k6'
          working-directory: ${{ github.workspace }}
          
      - name: Run Load tests
        uses: grafana/run-k6-action@v1
        env:
          K6_TEST_URL: http://localhost:8000
        with:
          path: |
            flights/k6/load.js
          flags: --vus 50 --duration 10s
          working-directory: ${{ github.workspace }}

      - name: Stop Wiremock
        if: always()
        run: |
          docker stop ${{ env.container_id }}
      
      