name: Contract Mock Testing

on:
  workflow_call:
    inputs:
      openapi_file:
        description: 'OpenAPI file path'
        type: string
        default: 'flights/openapi.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    name: Mock testing with inso, schemathesis and wiremock
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Wiremock
        id: setup-wiremock
        run: |
          container_id=$(docker run -d --rm \
          -p 8080:8080 \
          --name wiremock \
          -v ${{ github.workspace }}/mock:/home/wiremock \
          wiremock/wiremock:3.10.0)
          echo "container_id=$container_id" >> $GITHUB_ENV
      
      - name: Get the WireMock standard output
        run: echo "${{ steps.setup-wiremock.outputs.wiremock-stdout }}"

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          format: openapi
          target: 'flights/openapi.yaml'
          working-directory: ${{ github.workspace }}

      - name: Stop Wiremock
        if: always()
        run: |
          docker stop ${{ env.container_id }}
      
      