name: OAS to Kong

on:
  workflow_call:
    inputs:
      openapi_spec:
        description: "Path to the OpenAPI Specification file"
        required: true
        type: string

env:
  DECK_CONFIG_OIDC_ISSUER: ${{ secrets.OIDC_ISSUER }}

jobs:
  publish-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y_%m_%dT%H_%M_%S')" >> $GITHUB_ENV
      
      - name: Get a backup of the previous Kong Gateway configuration
        run: |
          deck gateway dump \
            --konnect-addr="${{ inputs.konnect_server_url }}" \
            --konnect-token="${{ steps.import-token.outputs.system_account_TOKEN }}" \
            --konnect-control-plane-name="${{ inputs.control_plane_name }}" -o kong_backup_${{ env.NOW }}.yaml
        working-directory: ${{ github.workspace }}/examples/apiops

      - name: Diff Kong Gateway configuration
        run: |
          deck gateway diff kong.yaml  \
            --konnect-addr="${{ inputs.konnect_server_url }}" \
            --konnect-token="${{ steps.import-token.outputs.system_account_TOKEN }}" \
            --konnect-control-plane-name="${{ inputs.control_plane_name }}" > diff_${{ env.NOW }}.txt
        working-directory: ${{ github.workspace }}/examples/apiops

      - name: Sync Kong Gateway configuration
        run: |
          deck gateway sync kong.yaml  \
            --konnect-addr="${{ inputs.konnect_server_url }}" \
            --konnect-token="${{ steps.import-token.outputs.system_account_TOKEN }}" \
            --konnect-control-plane-name="${{ inputs.control_plane_name }}"
        working-directory: ${{ github.workspace }}/examples/apiops

      - name: Get a backup of the current Kong Gateway configuration
        run: |
          deck gateway dump \
            --konnect-addr="${{ inputs.konnect_server_url }}" \
            --konnect-token="${{ steps.import-token.outputs.system_account_TOKEN }}" \
            --konnect-control-plane-name="${{ inputs.control_plane_name }}" -o kong_current_${{ env.NOW }}.yaml
        working-directory: ${{ github.workspace }}/examples/apiops

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            ${{ github.workspace }}/examples/apiops/kong_backup_${{ env.NOW }}.yaml
            ${{ github.workspace }}/examples/apiops/kong_current_${{ env.NOW }}.yaml
            ${{ github.workspace }}/examples/apiops/diff_${{ env.NOW }}.txt
            ${{ github.workspace }}/examples/apiops/oas_lint_results_${{ env.NOW }}.txt


      